services:
    builder:
        image: node:24-alpine
        restart: "no"
        volumes:
        - ./extensions/djspot-core:/extension
        working_dir: /extension
        command: sh -c "npm install && npm run build"
    mariadb:
        image: mariadb:11.8.3
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_uca1400_ai_ci
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: directus
        ports:
            - 5102:3306
        volumes:
            - ./mariadb_data:/var/lib/mysql
    directus:
        image: directus/directus:11.17.0
        ports:
            - 8055:8055
        volumes:
            - ./uploads:/directus/uploads
            - ./extensions:/directus/extensions
            - ./snapshots:/directus/snapshots
        environment:
            PUBLIC_URL: "http://localhost:3000"
            KEY: "2985a8f6-aba3-45ab-8c1b-f36599896125"
            SECRET: "Xmakb8JqJNCqPZsybNL3RHOsMxrPMwX-"
            ADMIN_EMAIL: "admin@example.com"
            ADMIN_PASSWORD: "pass"
            DB_CLIENT: "mysql"
            DB_HOST: "mariadb"
            DB_PORT: "3306"
            DB_DATABASE: "directus"
            DB_USER: "root"
            DB_PASSWORD: "secret"
            WEBSOCKETS_ENABLED: "true"
            EXTENSIONS_AUTO_RELOAD: true
            DIRECTUS_EXTENSIONS_PATH: /directus/extensions/
            EMAIL_TRANSPORT: "smtp"
            EMAIL_SMTP_HOST: "mailpit"
            EMAIL_SMTP_PORT: "1025"
            EMAIL_FROM: "admin@example.com"
            USER_REGISTER_URL_ALLOW_LIST: "http://localhost:3000/user/account-activation"
        healthcheck:
            test: ["CMD", "wget", "-q", "--spider", "http://127.0.0.1:8055/admin/login"]
            interval: 5s
            timeout: 20s
            retries: 10
        depends_on:
            builder:
                condition: service_completed_successfully

    schema-applier:
        image: directus/directus:11.17.0
        restart: "no"
        volumes:
            - ./snapshots:/directus/snapshots
        environment:
            DB_CLIENT: "mysql"
            DB_HOST: "mariadb"
            DB_PORT: "3306"
            DB_DATABASE: "directus"
            DB_USER: "root"
            DB_PASSWORD: "secret"
        command: npx directus schema apply --yes ./snapshots/latest-schema.yaml
        depends_on:
            directus:
                condition: service_healthy

    mailpit:
        image: axllent/mailpit
        ports:
            - 8025:8025
            - 1025:1025
